[build]
  publish = "frontend/dist"
  command = "npm run build --prefix frontend"

[functions]
  directory = "frontend/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200